version: "3.8"

services:
    dev-container:
        build:
            context: .
        working_dir: /usr/local/app
        command: sleep infinity
        volumes:
            - "..:/usr/local/app"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}

    web-api:
        build:
            context: ../web-api
        ports:
            - "5000:5000"

    web-app:
        build:
            context: ../web-app
        ports:
            - "5010:5010"

    db:
        build:
            context: ../db
        ports:
            - "5020:5432"
            